### PR TITLE
We want to use LGTM.co for approval

### PR DESCRIPTION
**Pull request by krainboltgreene**
@vcr/core Now's your chance to get in on this.

### CODE REVIEW

**Comment by krainboltgreene** [comment]
LGTM

**Comment by mcfiredrill** [comment]
LGTM

**Comment by mislav** [comment]
Will all people listed have to give their approval?

**Comment by ecnalyr** [comment]
> Will all people listed have to give their approval?

**Comment by krainboltgreene** [comment]
No, only 2 approvers are required. Amusingly the submitter, if in the list,
can be one of those.

**Comment by mcfiredrill** [comment]
@krainboltgreene Do you know if LGTM has any settings to change that? It feels a little silly having to LGTM my own PR... :sweat_smile:

**Comment by krainboltgreene** [comment]
@mcfiredrill I'm talking to them about it now. Realistically you'd just get someone else to :+1: it :)

**Pull request merged**
