### PR TITLE
remove 1.8.7 support from specs

### PR DESCRIPTION
**Pull request by mcfiredrill**
Since we removed support for 1.8.7 we don't need this check in the specs.

### CODE REVIEW

**Comment by krainboltgreene** [comment]
:+1:

**Comment by mcfiredrill** [comment]
:+1:

**Comment by mcfiredrill** [comment]
@krainboltgreene is this LGTM thing not working? There are two :+1: 's on this PR. I thought that was all that is needed to merge.

**Comment by krainboltgreene** [comment]
@mcfiredrill It's working fine. The tests are failing, but you're free to merge.

**Comment by mcfiredrill** [comment]
@krainboltgreene Yeah the merge button was not clickable (grayed out) for me...
but thanks for merging :+1:

**Comment by krainboltgreene** [comment]
Hrm, okay, we should figure that out. I'll look a it later today.

**Pull request merged**
