### PR TITLE
Get CI passing again

### LINKED ISSUE #502: Upgrade Faraday gem to 0.9.1
Fix #500 downgraded Faraday to 0.9.0, VCR should be on the latest version.

### LINKED ISSUE #503: Support Ruby 2.2.x
100+ failing tests when using Ruby 2.2.0 and 2.2.1:

```
2110 examples, 106 failures, 2 pending

Failed examples:

rspec ./spec/lib/vcr/cassette/serializers_spec.rb[1:1:2:1:1] # VCR::Cassette::Serializers behaves like a serializer behaves like encoding error handling the yaml serializer appends info about the :preserve_exact_body_bytes option to the error
rspec ./spec/lib/vcr/cassette/serializers_spec.rb:161 # VCR::Cassette::Serializers psych serializer serializes things using pysch even if syck is configured as the default YAML engine
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:6] # WebMock hook behaves like a hook into an HTTP library using Patron plays back an empty body response exactly as it was recorded (e.g. nil vs empty string)
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:8] # WebMock hook behaves like a hook into an HTTP library using Patron does not query the http interaction list excessively
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:1:1] # WebMock hook behaves like a hook into an HTTP library using Patron making an HTTP request that responds with 1 Set-Cookie header(s) returns the same header value when recording and replaying
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:2:1] # WebMock hook behaves like a hook into an HTTP library using Patron making an HTTP request that responds with 2 Set-Cookie header(s) returns the same header value when recording and replaying
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:3:1] # WebMock hook behaves like a hook into an HTTP library using Patron a request to a URL with spaces encoded as + properly records and playsback a request with a URL with spaces encoded as +
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:4:1] # WebMock hook behaves like a hook into an HTTP library using Patron a request to a URL with spaces encoded as %20 properly records and playsback a request with a URL with spaces encoded as %20
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:5:1] # WebMock hook behaves like a hook into an HTTP library using Patron a request to a URL with a complex escaped query param properly records and playsback a request with a URL with a complex escaped query param
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:9:1] # WebMock hook behaves like a hook into an HTTP library using Patron using the library's stubbing/disconnection APIs can make a real request when VCR is turned off
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:9:2] # WebMock hook behaves like a hook into an HTTP library using Patron using the library's stubbing/disconnection APIs does not mess with VCR when real connections are disabled
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:2] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks correctly assigns the correct type to both before and after request hooks, even if they are different
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:1:1] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when there is an around_http_request hook yields the request to the block
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:1:2] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when there is an around_http_request hook returns the response from request.proceed
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:1:3] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when there is an around_http_request hook can be used to use a cassette for a request
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:1:4] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when there is an around_http_request hook nests them inside each other, making the first declared hook the outermost
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:1:5] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when there is an around_http_request hook raises an appropriate error if the hook does not call request.proceed
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:1:6] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when there is an around_http_request hook does not get a dead fiber error when multiple requests are made
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:1:7] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when there is an around_http_request hook allows the hook to be filtered
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:1:8] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when there is an around_http_request hook ensures that both around/before are invoked or neither
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:3:1:1] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is ignored behaves like request hooks the before_http_request hook is only called once per request
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:3:1:2] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is ignored behaves like request hooks the before_http_request hook yields the request
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:3:1:3] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is ignored behaves like request hooks the before_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:3:1:4] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is ignored behaves like request hooks the #type of the yielded request given to the before_http_request hook is ignored
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:3:1:5] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is ignored behaves like request hooks the after_http_request hook is only called once per request
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:3:1:6] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is ignored behaves like request hooks the after_http_request hook yields the request
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:3:1:7] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is ignored behaves like request hooks the after_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:3:1:8] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is ignored behaves like request hooks the #type of the yielded request given to the after_http_request hook is ignored
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:3:1:9] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is ignored behaves like request hooks the after_http_request hook yields the response if there is one and the second block arg is given
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:5:1:1] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is recorded behaves like request hooks the before_http_request hook is only called once per request
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:5:1:2] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is recorded behaves like request hooks the before_http_request hook yields the request
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:5:1:3] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is recorded behaves like request hooks the before_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:5:1:4] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is recorded behaves like request hooks the #type of the yielded request given to the before_http_request hook is recordable
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:5:1:5] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is recorded behaves like request hooks the after_http_request hook is only called once per request
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:5:1:6] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is recorded behaves like request hooks the after_http_request hook yields the request
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:5:1:7] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is recorded behaves like request hooks the after_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:5:1:8] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is recorded behaves like request hooks the #type of the yielded request given to the after_http_request hook is recordable
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:5:1:9] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is recorded behaves like request hooks the after_http_request hook yields the response if there is one and the second block arg is given
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:5:1:11] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is recorded behaves like request hooks the after_http_request hook can be used to eject a cassette after the request is recorded
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:6:1:3] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when a stubbed response is played back for the request behaves like request hooks the before_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:6:1:7] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when a stubbed response is played back for the request behaves like request hooks the after_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:7:1:3] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is not allowed behaves like request hooks the before_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:10:7:1:7] # WebMock hook behaves like a hook into an HTTP library using Patron request hooks when the request is not allowed behaves like request hooks the after_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:12:1] # WebMock hook behaves like a hook into an HTTP library using Patron when VCR.real_http_connections_allowed? is returning true allows real http requests
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:12:2:1] # WebMock hook behaves like a hook into an HTTP library using Patron when VCR.real_http_connections_allowed? is returning true recording new http requests does not record the request if the hook is disabled
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:12:2:2] # WebMock hook behaves like a hook into an HTTP library using Patron when VCR.real_http_connections_allowed? is returning true recording new http requests records the request uri
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:12:2:3] # WebMock hook behaves like a hook into an HTTP library using Patron when VCR.real_http_connections_allowed? is returning true recording new http requests records the request method
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:12:2:4] # WebMock hook behaves like a hook into an HTTP library using Patron when VCR.real_http_connections_allowed? is returning true recording new http requests records the request body
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:12:2:5] # WebMock hook behaves like a hook into an HTTP library using Patron when VCR.real_http_connections_allowed? is returning true recording new http requests records the request headers
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:12:2:6] # WebMock hook behaves like a hook into an HTTP library using Patron when VCR.real_http_connections_allowed? is returning true recording new http requests records the response status code
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:12:2:7] # WebMock hook behaves like a hook into an HTTP library using Patron when VCR.real_http_connections_allowed? is returning true recording new http requests records the response status message
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:12:2:8] # WebMock hook behaves like a hook into an HTTP library using Patron when VCR.real_http_connections_allowed? is returning true recording new http requests records the response body
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:12:2:9] # WebMock hook behaves like a hook into an HTTP library using Patron when VCR.real_http_connections_allowed? is returning true recording new http requests records the response headers
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:13:2:1] # WebMock hook behaves like a hook into an HTTP library using Patron when VCR.real_http_connections_allowed? is returning false when ignore_hosts is configured to "127.0.0.1", "localhost" allows requests to 127.0.0.1
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:4:1:13:2:2] # WebMock hook behaves like a hook into an HTTP library using Patron when VCR.real_http_connections_allowed? is returning false when ignore_hosts is configured to "127.0.0.1", "localhost" allows requests to localhost
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:5:1:1] # WebMock hook using Patron when real connections are disabled and VCR is turned off can allow connections to localhost
rspec ./spec/lib/vcr/library_hooks/webmock_spec.rb[1:5:1:2] # WebMock hook using Patron when real connections are disabled and VCR is turned off can allow connections to matching urls
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:6] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) plays back an empty body response exactly as it was recorded (e.g. nil vs empty string)
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:8] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) does not query the http interaction list excessively
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:1:1] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) making an HTTP request that responds with 1 Set-Cookie header(s) returns the same header value when recording and replaying
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:2:1] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) making an HTTP request that responds with 2 Set-Cookie header(s) returns the same header value when recording and replaying
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:3:1] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) a request to a URL with spaces encoded as + properly records and playsback a request with a URL with spaces encoded as +
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:4:1] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) a request to a URL with spaces encoded as %20 properly records and playsback a request with a URL with spaces encoded as %20
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:5:1] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) a request to a URL with a complex escaped query param properly records and playsback a request with a URL with a complex escaped query param
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:2] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks correctly assigns the correct type to both before and after request hooks, even if they are different
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:1:1] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when there is an around_http_request hook yields the request to the block
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:1:2] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when there is an around_http_request hook returns the response from request.proceed
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:1:3] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when there is an around_http_request hook can be used to use a cassette for a request
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:1:4] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when there is an around_http_request hook nests them inside each other, making the first declared hook the outermost
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:1:6] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when there is an around_http_request hook does not get a dead fiber error when multiple requests are made
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:1:7] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when there is an around_http_request hook allows the hook to be filtered
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:1:8] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when there is an around_http_request hook ensures that both around/before are invoked or neither
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:3:1:1] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is ignored behaves like request hooks the before_http_request hook is only called once per request
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:3:1:2] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is ignored behaves like request hooks the before_http_request hook yields the request
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:3:1:3] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is ignored behaves like request hooks the before_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:3:1:4] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is ignored behaves like request hooks the #type of the yielded request given to the before_http_request hook is ignored
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:3:1:5] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is ignored behaves like request hooks the after_http_request hook is only called once per request
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:3:1:6] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is ignored behaves like request hooks the after_http_request hook yields the request
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:3:1:7] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is ignored behaves like request hooks the after_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:3:1:8] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is ignored behaves like request hooks the #type of the yielded request given to the after_http_request hook is ignored
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:3:1:9] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is ignored behaves like request hooks the after_http_request hook yields the response if there is one and the second block arg is given
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:4:1:1] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is recorded behaves like request hooks the before_http_request hook is only called once per request
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:4:1:2] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is recorded behaves like request hooks the before_http_request hook yields the request
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:4:1:3] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is recorded behaves like request hooks the before_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:4:1:4] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is recorded behaves like request hooks the #type of the yielded request given to the before_http_request hook is recordable
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:4:1:5] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is recorded behaves like request hooks the after_http_request hook is only called once per request
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:4:1:6] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is recorded behaves like request hooks the after_http_request hook yields the request
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:4:1:7] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is recorded behaves like request hooks the after_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:4:1:8] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is recorded behaves like request hooks the #type of the yielded request given to the after_http_request hook is recordable
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:4:1:9] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is recorded behaves like request hooks the after_http_request hook yields the response if there is one and the second block arg is given
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:4:1:11] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is recorded behaves like request hooks the after_http_request hook can be used to eject a cassette after the request is recorded
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:5:1:3] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when a stubbed response is played back for the request behaves like request hooks the before_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:5:1:7] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when a stubbed response is played back for the request behaves like request hooks the after_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:6:1:3] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is not allowed behaves like request hooks the before_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:10:6:1:7] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) request hooks when the request is not allowed behaves like request hooks the after_http_request hook is not called if the library hook is disabled
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:12:1] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) when VCR.real_http_connections_allowed? is returning true allows real http requests
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:12:2:1] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) when VCR.real_http_connections_allowed? is returning true recording new http requests does not record the request if the hook is disabled
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:12:2:2] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) when VCR.real_http_connections_allowed? is returning true recording new http requests records the request uri
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:12:2:3] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) when VCR.real_http_connections_allowed? is returning true recording new http requests records the request method
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:12:2:4] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) when VCR.real_http_connections_allowed? is returning true recording new http requests records the request body
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:12:2:5] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) when VCR.real_http_connections_allowed? is returning true recording new http requests records the request headers
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:12:2:6] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) when VCR.real_http_connections_allowed? is returning true recording new http requests records the response status code
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:12:2:7] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) when VCR.real_http_connections_allowed? is returning true recording new http requests records the response body
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:12:2:8] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) when VCR.real_http_connections_allowed? is returning true recording new http requests records the response headers
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:13:2:1] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) when VCR.real_http_connections_allowed? is returning false when ignore_hosts is configured to "127.0.0.1", "localhost" allows requests to 127.0.0.1
rspec ./spec/lib/vcr/middleware/faraday_spec.rb[1:3:1:13:2:2] # VCR::Middleware::Faraday behaves like a hook into an HTTP library using Faraday (patron) when VCR.real_http_connections_allowed? is returning false when ignore_hosts is configured to "127.0.0.1", "localhost" allows requests to localhost
```

### PR DESCRIPTION
**Pull request by mislav**
* Compatibility with Ruby 2.2
* Compatibility with new versions of Cucumber
* Brings back `script/ci.sh` in CI for full running of specs + cukes + compatibility with legacy versions of Faraday/Typhoeus/Cucumber
* Drops 1.9.2 from CI testing because Cucumber is not compatible
* Faraday compatibility in tests (by bumping Faraday to 0.9.2)

Fixes #497, fixes #500, fixes #502, fixes #503, fixes #363

### CODE REVIEW

**Comment by mislav** [comment]
@krainboltgreene Can we please disable Hound CI? I don't find those warnings useful.

**Comment by krainboltgreene** [comment]
Yeah, same. I'll do it tonight.

On Tue, Oct 6, 2015 at 10:27 AM, Mislav Marohnić <notifications@github.com>
wrote:

> @krainboltgreene <https://github.com/krainboltgreene> Can we please
> disable Hound CI? I don't find those warnings useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vcr/vcr/pull/511#issuecomment-145935395>.
>



-- 
Kurtis Rainbolt-Greene, Hacker
Software Developer
1631 8th St.
New Orleans, LA
70115

**Comment by myronmarston** [comment]
Amazing work, @mislav!  Thank you so much!

:heart: :heart: :heart:

@krainboltgreene -- now that the build is actually green, it would be nice to cut a release to get the faraday 0.9 fixes (and whatever else is in master) out there.  I think you are all setup to cut releases but let me know if you want to pair on doing the first release.

**Comment by krainboltgreene** [comment]
Nah, I've done gem releases before, but thanks!

**Comment by krainboltgreene** [comment]
@mislav You are awesome!

**Comment by mislav** [comment]
There's literally just one fix in actual lib directory in this PR, and that's Cucumber 2 integration when it comes to scenario outlines. But yeah, definitely warrants a patch release soon.

**Comment by krainboltgreene** [comment]
Just as an update, getting some FOSS stuff cleaned up and a release of VCR is on my TODO.

**Comment by krainboltgreene** [comment]
Release out.

**Pull request merged**
