### PR TITLE
remove 1.9.3 from build matrix

### PR DESCRIPTION
**Pull request by mcfiredrill**
https://github.com/vcr/vcr/issues/577

### CODE REVIEW

**Comment by mcfiredrill** [comment]
Hmm failing on 2.0, not sure why. :(

**Comment by ecnalyr** [comment]
Why'd you give up on this?

**Comment by mcfiredrill** [comment]
@ecnalyr  on 1.9.3? or the 2.0 build failure?

**Comment by ecnalyr** [comment]
Removing 1.9.3 from travis.yml.

**Comment by mcfiredrill** [comment]
Honestly I'm open to supporting it, 
VCR is a pretty old library, I guess some of its value is in its legacy and supporting old rubies might be part of that. I opened an issue about dropping 1.9.3 support and didn't get much feedback other than some +1s. 
https://github.com/vcr/vcr/issues/577

Any thoughts?

**Comment by mcfiredrill** [comment]
That said the main argument for dropping 1.9.3 is that it is EOL, as I'm sure you know.

**Comment by ecnalyr** [comment]
It seems like we have a tough time keeping maintainers contributing to the codebase, supporting versions of ruby that are beyond the end of their life seems like a good way to continue to make people hesitant to contribute.

I'm all for removing it.  We have old versions of VCR that aren't going anywhere if someone needs legacy support.

**Comment by ecnalyr** [comment]
@mcfiredrill - I totally misunderstood this thread.

I got my branches mixed up and assumed you had closed this without merging (I saw the deleted message above, but did not see the merged message above that).

Sorry for the misunderstanding.

I am glad you removed 1.9.3 from the list of builds.  Ignore everything else that is here.

**Comment by mcfiredrill** [comment]
@ecnalyr Ah I see, thanks for your response anyway it helps. 👍

**Pull request merged**
