### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### vcr/vcr now has a Chat Room on Gitter

@krainboltgreene has just created a chat room. You can visit it here: [https://gitter.im/vcr/vcr](https://gitter.im/vcr/vcr?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/vcr/vcr?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by mcfiredrill** [comment]
@krainboltgreene Not sure why this PR has conflicts, should we close it and open a new PR to add the badge?

**Comment by ecnalyr** [comment]
> Not sure why this PR has conflicts, should we close it and open a new PR to add the badge?

Because it does a lot more than just add the badge.  There are many changes to the readme in one commit.  

Maybe the pr description should be updated to include details about the additional changes beyond  the badge adjustment.

**Comment by mcfiredrill** [comment]
@ecnalyr Yeah, I mean I don't know why gitter's PR bot added all those changes.

**Comment by ecnalyr** [comment]
I'd opt to just close it.

**Comment by krainboltgreene** [comment]
Yah, I'll close it when I get home. By the way, good time to ask: do any of
you all want commit privs? It's a large library.

**Comment by mcfiredrill** [comment]
@krainboltgreene I'm not sure if I'm quite ready to commit code, but I think I could definitely help out managing issues and other chores. :bow:

**Comment by ecnalyr** [comment]
I use VCR all the time, I wouldn't mind commit privileges if you're handing them out.

**Pull request closed without merging**
