### PR TITLE
release version 3.0.1 of VCR

### PR DESCRIPTION
**Pull request by mcfiredrill**
Did I miss anything in the CHANGELOG? The two things I mentioned seemed
like the biggest changes.

### CODE REVIEW

**Comment by krainboltgreene** [comment]
I prefer matching the style in 3.0.0

**Comment by mcfiredrill** [comment]
I was just trying to match the style of the rest of the file.

**Comment by mcfiredrill** [comment]
There's no real style guide on rubygems for how your changelog should be formatted...
http://guides.rubygems.org/patterns/#semantic-versioning

That said, is there a reason you want to change the format? I don't see why we really need to change it.

At the least, it would be nice to use "##" for the version numbers:
https://github.com/vcr/vcr/pull/532/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR16
makes the file a little easier to scan for the version number you are interested in reading about.

**Comment by mcfiredrill** [comment]
@krainboltgreene changed the format of the changelog, what do you think?

**Comment by krainboltgreene** [comment]
:+1:

**Comment by krainboltgreene** [comment]
:+1:

**Comment by krainboltgreene** [comment]
@mcfiredrill You'll need to +1 this.

**Comment by mcfiredrill** [comment]
We have to +1 our own PRs? :\

:+1:

**Comment by krainboltgreene** [comment]
Well also you have to update from master.

**Comment by mcfiredrill** [comment]
@krainboltgreene rebased

**Pull request merged**
