### PR TITLE
Fix on_body issue for Typhoeus w/ code style changes

### PR DESCRIPTION
**Pull request by ikapelyukhin**
#614 with the requested code style changes. Addresses #509.

### CODE REVIEW

**Comment by ikapelyukhin** [comment]
This spec is failing:

```
rspec ./spec/lib/vcr/library_hooks/typhoeus_spec.rb:86 # Typhoeus hook when used with a typhoeus-based faraday connection records and replays headers correctly
```

But it's failing in master too ¯\_(ツ)_/¯

**Comment by ikapelyukhin** [comment]
@ecnalyr I've implemented the changes you've requested in #614, please take a look.

**Comment by mcfiredrill** [comment]
Thanks for your PR.
I'm honestly wondering if we should keep supporting typheous in future versions.
https://github.com/vcr/vcr/issues/464#issuecomment-68910577

**Comment by ikapelyukhin** [comment]
@mcfiredrill why wouldn't you keep it? Typhoeus is a wrapper of libcurl, which probably is the most widely-used HTTP client across different languages and platforms.

The comment you've referenced is talking specifically about dropping `Support for Typhoeus <= 0.4.` -- the current version of Typhoeus is 1.1.2. Dropping support for legacy versions isn't quite the same as dropping support for it completely. :-)

I've used the code in this pull request and have been able to record the cassette successfully.

**Comment by mcfiredrill** [comment]
@ikapelyukhin 
Thanks for clearing that up! I overlooked that the comment was talking about an old version.

I'm OK to merge this but any idea why the build is failing?

**Comment by ikapelyukhin** [comment]
@mcfiredrill I'm not sure. As I've mentioned -- the same spec seems to fail in master as well (that's why I haven't looked into it).

**Comment by mcfiredrill** [comment]
@ikapelyukhin I will try to get master passing

**Comment by ikapelyukhin** [comment]
I've fixed a couple of other issues:

- Response body wasn't recorded if a there was on_body callback that returned `:abort`
- `on_headers` and `on_body` callbacks weren't invoked when playing back the cassette

**Comment by ikapelyukhin** [comment]
@mcfiredrill I've fixed the issue with the broken Faraday spec in #657.

**Comment by ikapelyukhin** [comment]
Rebased the branch, let's see if any tests flicker again.

**Comment by ikapelyukhin** [comment]
@mcfiredrill All green!

**Comment by mcfiredrill** [comment]
Looking good, thanks for your work!

**Comment by ikapelyukhin** [comment]
@mcfiredrill no problem. Any plans for the next version release?

**Comment by mcfiredrill** [comment]
We've been due for one for a bit, I will get to releasing 4.0 as soon as I can. 🙇

**Comment by mcfiredrill** [comment]
BTW I had a TODO list for 4.0 but I think everything is basically doone.
https://github.com/vcr/vcr/issues/578

**Comment by ikapelyukhin** [comment]
Sounds good! :+1:

**Comment by ikapelyukhin** [comment]
@mcfiredrill any word on 4.0 release? Need a hand with anything, maybe? :grimacing:

**Pull request merged**
