### PR TITLE
Update Aruba

### PR DESCRIPTION
**Pull request by mvz**
This is a based on #772 and fixes the remaining deprecation warnings and test failures.

### CODE REVIEW

**Comment by olleolleolle** [comment]
I am going to squash-and-merge this to master now, and I'd like to thank @mvz for painstakingly doing this work.

**Comment by mvz** [comment]
Hm, maybe we should check the build failure first?

**Comment by olleolleolle** [comment]
@mvz https://github.com/vcr/vcr/pull/781 is a fix for that.

**Comment by mvz** [comment]
(And I hate squash merging :man_shrugging:)

**Comment by olleolleolle** [comment]
> (And I hate squash merging 🤷‍♂)

It's the only available allowed PR merge option configured in this repository.

**Comment by mvz** [comment]
> @mvz #781 is a fix for that.

Can we check that this PR builds with that?

**Comment by olleolleolle** [comment]
OK, trying again, now `master` has the change which made the build green again.

**Comment by olleolleolle** [comment]
All green! 🍏

**Pull request merged**
