### PR TITLE
rbenv complains if version specified is not exact

### PR DESCRIPTION
**Pull request by asymmetric**
There are several matches for 2.1: 2.1.0, 2.1.1, etc.

rbenv/ruby-install is more precise than other ruby version managers (ahem) and doesn't proceed with the installation.

### CODE REVIEW

**Comment by tylercollier** [comment]
+1. Yes, it's curious as to why 2.1 was chosen. Why not e.g. 2.1.0?

**Comment by sigmavirus24** [comment]
Likely because the developers don't use rbenv. I know that at least rvm will pick the latest 2.1.* if you only put 2.1 in the ruby-version file. This means that you can have the latest 2.x.* with all the latest CVE fixes without having to also carry old, out of date, and vulnerable versions of ruby.

**Comment by krainboltgreene** [comment]
Grumble grumble. Yes I don't use rbenv, yes it's because I assumed it would handle like `~> 2.1.0`, since that's how Ruby's versioning works now.

**Comment by krainboltgreene** [comment]
I don't want to alienate rbenv users, so I'm just going to suck it up and install a specific verison of ruby for vcr. Sorry for this problem!

**Comment by mislav** [comment]
@krainboltgreene Could we just remove `.ruby-version`? This library is compatible with all currently maintained Ruby releases. It doesn't matter which one somebody uses in development.

**Comment by krainboltgreene** [comment]
I mean, I like having `.ruby-version`, but yes, you're right in that any ruby version should currently work with vcr.

**Comment by mislav** [comment]
Yeah, let's not force people to install a specific Ruby version when not necessary.

**Pull request merged**
