### PR TITLE
remove .gemtest file

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by mcfiredrill** [comment]
I was about to make a PR for this lol... :dango:

**Comment by mcfiredrill** [comment]
@nikolas remove the rake task too?
https://github.com/vcr/vcr/commit/1aa5b6d98125d292e68dbf8e473ecc1031368302

**Comment by nikolas** [comment]
:bee:

**Comment by nikolas** [comment]
@mcfiredrill that rake task isn't in the current rakefile

**Comment by mcfiredrill** [comment]
Ah ok cool, then I think its definitely ok to remove this, I can't figure out with gem-testers.org was.. :\

**Comment by mcfiredrill** [comment]
@nikolas Thanks

**Pull request merged**
