### PR TITLE
fix for Faraday 0.9.x

### PR DESCRIPTION
**Pull request by TimothyKlim**

### CODE REVIEW

**Comment by jirutka** [comment]
What’s the current state of this issue? Why VCR doesn’t support faraday 0.9.x?

**Comment by bentona** [comment]
@myronmarston are there any plans to support Faraday 0.9.x?

**Comment by myronmarston** [comment]
I do not maintain VCR anymore.  You will have to ask @krainboltgreene.

**Comment by chriswoodrich** [comment]
@bentona I'm working on it.  Got it working with 0.9.0, but not yet 0.9.1.

**Pull request closed without merging**
