### PR TITLE
Make VCR thread-safe

### PR DESCRIPTION
**Pull request by mrbrdo**
Trying to finally get rid of this problem. Seems to work well with my test case.
This is for the case when the code being tested is threaded, not for running tests in threads.

CC https://github.com/vcr/vcr/issues/200

### CODE REVIEW

**Comment by myronmarston** [comment]
I just deactivated hound.  Sorry about the noise.

**Comment by mrbrdo** [comment]
I wanted to get the specs passing for JRuby as well, but I can't figure out a way to only require curb, yajl-ruby and patron on MRI. I tried putting them into the Gemfile instead of the gemspec and that worked fine locally (and specs are all passing), but Travis then didn't use any of these gems even under MRI (bundle install did not include those gems in the output, and then the require failed in the specs).

**Comment by mrbrdo** [comment]
I think this PR also solves #494 and #376

**Comment by Fryguy** [comment]
:clap: Happy to see this!

**Comment by mrbrdo** [comment]
Yes me too. :)

Thanks to Daniel Berger for the bounty which enabled this PR: http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-talk/433878

**Comment by krainboltgreene** [comment]
Release out.

**Comment by mrbrdo** [comment]
:fireworks:

**Comment by perlun** [comment]
Sorry to be a party killer here, but... there are still issues. I'm running into #368 even with the latest version. Or is there anything I'm missing here, are there still threading issues when testing code that is multi-threaded?

**Pull request merged**
