### PR TITLE
remove .ruby-version

### PR DESCRIPTION
**Pull request by mcfiredrill**
VCR should work on all currently maintained ruby versions. I propose we
delete this file.

### CODE REVIEW

**Comment by krainboltgreene** [comment]
While it should, there's a lot of barrier to entry that this file removes for new people who want to contribute.

**Comment by mcfiredrill** [comment]
Can you explain what you mean? I'd say this file *is* a barrier to entry, rather than removing barriers. They might not have the exact version installed.

**Comment by mislav** [comment]
:+1: 

A `.ruby-version` file is not needed for a project that will work with any Ruby version. It just **adds a barrier to entry** because now people have to install a specific Ruby version, even though they probably already had a perfectly valid Ruby to start developing with.

**Comment by krainboltgreene** [comment]
I have to disagree here. I've seen plenty of new developers not able to really figure out what to do at start and the `.ruby-version` file gives them a clear indication on how to start. If they've got rvm installed (highly likely) it *literally gives them the command to run*.

That said, I'll abide by the votes if it gets a second plus one.

**Comment by mislav** [comment]
I can't imagine someone new to Ruby development (and thus having no Ruby versions installed) picking up VCR and starting hacking on it. VCR is a fairly advanced piece of software. I would guess that whoever plays with it already has a development environment set up.

**Comment by mcfiredrill** [comment]
:+1:

**Comment by shaicoleman** [comment]
I think it's better to remove it. It forces using an arbitrary and specific old version of Ruby.

Standard practice is not to include a .ruby-version, and add it in .gitignore for libraries meant to run on multiple versions.

Example: https://github.com/github/gitignore/blob/master/Ruby.gitignore

**Comment by mcfiredrill** [comment]
@shaicoleman :+1:

**Comment by mcfiredrill** [comment]
@krainboltgreene  I mean on this PR for example, looks like the status check from LGTM is still here.

Not sure if we can remove it without starting a new PR... :sweat:

**Comment by krainboltgreene** [comment]
@mcfiredrill Tada!

**Comment by mcfiredrill** [comment]
@krainboltgreene wow, :sparkles: :heart_eyes_cat:

**Comment by mcfiredrill** [comment]
@krainboltgreene I don't know what you did but thank you! :green_heart:

**Pull request merged**
