### PR TITLE
Faraday 0.9 compatibility

### LINKED ISSUE #386: VCR 2.8 w/ Faraday 0.9.0 Failures After Upgrading
As much help as 'VCR 2.8 w/ Faraday 0.9.0 Failures After Upgrading' is, I think a backtrace would be a bit more helpful :smile:

FWIW, Faraday 0.8.9 works correctly.

```
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `to_hash' for nil:NilClass
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/vcr-2.8.0/lib/vcr/structs.rb:497:in `to_hash'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/vcr-2.8.0/lib/vcr/cassette.rb:116:in `map'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/vcr-2.8.0/lib/vcr/cassette.rb:116:in `serializable_hash'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/vcr-2.8.0/lib/vcr/cassette.rb:254:in `write_recorded_interactions_to_disk'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/vcr-2.8.0/lib/vcr/cassette.rb:65:in `eject'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/vcr-2.8.0/lib/vcr.rb:149:in `eject_cassette'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/vcr-2.8.0/lib/vcr/test_frameworks/rspec.rb:35:in `block (2 levels) in configure!'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:471:in `instance_eval'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:471:in `instance_eval_with_rescue'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:242:in `instance_eval_with_rescue'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:31:in `run'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:85:in `block in run'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:85:in `each'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:85:in `run'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:446:in `run_hook'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:350:in `run_after_each_hooks'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:298:in `run_after_each'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:120:in `block in run'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:111:in `run'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:390:in `block in run_examples'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:386:in `map'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:386:in `run_examples'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:371:in `run'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:28:in `map'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:28:in `block in run'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/reporter.rb:58:in `report'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:25:in `run'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:80:in `run'
     # /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:17:in `block in autorun'
```

### PR DESCRIPTION
**Pull request by mislav**
CI will unfortunately intermittently fail (it did so prior to this PR) so I'll just merge this in spite of that when I get some review.

Changes aimed to stabilize our CI situation are coming in a separate PR.

Fixes #386

/cc @jfelchner @sferik @jjb

### CODE REVIEW

**Comment by pho3nixf1re** [comment]
Is there a time frame for when this fix will get a tagged release?

**Comment by myronmarston** [comment]
> Is there a time frame for when this fix will get a tagged release?

I had planned to release with this as soon as we got a green travis build but that hasn't happened yet.  In addition, I no longer have the time or energy to maintain VCR and it needs a new maintainer (as I've [announced on twitter](https://twitter.com/myronmarston/status/537687409295912962) and in the [README](https://github.com/vcr/vcr#new-maintainers-needed)).

In all likelihood, this will probably never get released unless someone steps forward to maintain VCR, which hasn't happened yet.

**Comment by jfelchner** [comment]
@myronmarston you have your hands full with RSpec.  What kind of average time commitment are we talking about?  Is it in need of reworking?

**Comment by ndushay** [comment]
+1 for a gem release with this fix in it ...

**Comment by krainboltgreene** [comment]
I'll look into this, but really faraday isn't going to be around much
longer. They're refactoring it into a new framework. You should consider
looking at that new library.

**Comment by ndushay** [comment]
@krainboltgreene thanks for the info.  where do i look for the new stuff?

**Comment by krainboltgreene** [comment]
https://github.com/lostisland/faraday/issues/454

**Pull request merged**
