### PR TITLE
Add go-vcr to the list of VCR ports

### PR DESCRIPTION
**Pull request by dnaeon**

### CODE REVIEW

**Comment by mcfiredrill** [comment]
LGTM

**Comment by krainboltgreene** [comment]
:+1:

**Comment by krainboltgreene** [comment]
Testing :+1:

**Comment by krainboltgreene** [comment]
Okay, @dnaeon just update your branch please.

**Comment by dnaeon** [comment]
@krainboltgreene I've just  rebased my branch against the current master of vcr and updated the PR.

Thanks,
Marin

**Pull request merged**
