### PR TITLE
prepare 4.0.0 release

### PR DESCRIPTION
**Pull request by mcfiredrill**
https://github.com/vcr/vcr/issues/578

### CODE REVIEW

**Comment by ikapelyukhin** [comment]
:neckbeard::+1:

**Comment by krainboltgreene** [comment]
We *just* recently fixed a big issue with the tests. Hmm...

**Comment by mcfiredrill** [comment]
No idea what the error is, look like the sinatra app is not starting properly maybe?
https://travis-ci.org/vcr/vcr/jobs/295664161#L1111

**Comment by ecnalyr** [comment]
A rebase should correct these test failures.

**Comment by krainboltgreene** [comment]
Rebased, but there's also more coming in. Can someone give me the highlights?

**Comment by ecnalyr** [comment]
Recent changes were:

- [Output non-matched headers on error.](https://github.com/vcr/vcr/pull/670)
- stuff to fix broken tests
- an update to the 'homepage'

The only thing, if any, that is note-worthy is the first point.

**Comment by krainboltgreene** [comment]
Okay, I'll release tonight when I have the time.

**Pull request merged**
