### PR TITLE
PR to improve the debug message (Unhanded request error)

### PR DESCRIPTION
**Pull request by dnesteryuk**
This PR allows us to see names and parameters of all cassettes in the stack. Example:

```
================================================================================
       An HTTP request has been made that VCR does not know how to handle:
         GET http://google.com/client/api?listAll=true&page=2&pagesize=20&response=json
  Body:
       
       VCR are currently using the following cassettes:
         - /home/dnesteryuk/projects/vcr/tmp/cassette_library_dir/sample.yml
           - :record => :once
           - :match_requests_on => [:method, :uri]
         - /home/dnesteryuk/projects/vcr/tmp/cassette_library_dir/example.yml
           - :record => :new_episodes
           - :match_requests_on => [:method, :uri]
       
       Under the current configuration VCR can not find a suitable HTTP interaction
       to replay and is prevented from recording new requests. There are a few ways
       you can deal with this:
       
         * If you're surprised VCR is raising this error
           and want insight about how VCR attempted to handle the request,
           you can use the debug_logger configuration option to log more details [1].
         * You can use the :new_episodes record mode to allow VCR to
           record this new request to the existing cassette [2].
         * If you want VCR to ignore this request (and others like it), you can
           set an `ignore_request` callback [3].
       
       [1] https://www.relishapp.com/vcr/vcr/v/2-9-3/docs/configuration/debug-logging
       [2] https://www.relishapp.com/vcr/vcr/v/2-9-3/docs/record-modes/new-episodes
       [3] https://www.relishapp.com/vcr/vcr/v/2-9-3/docs/configuration/ignore-request
       ================================================================================
```

It gives better understanding what is used for stubbing HTTP requests. This change was discussed here #478.

### CODE REVIEW

**Comment by dnesteryuk** [comment]
I see a lot of notes from HoundCI, should I work on them? If so, the full code base should be updated, because those issues are common for other parts of the project as well.

**Comment by krainboltgreene** [comment]
@dnesteryuk Sorry this took me so long to respond to, I somehow had notifications turned off. I don't anymore. Update from core and we're good!

**Comment by ecnalyr** [comment]
Trying to help clean up. . .

> I don't anymore. 

Did you mean: "I don't care anymore."   ?

> Update from core and we're good!

What do you mean by this?

**Comment by mcfiredrill** [comment]
@ecnalyr I think he meant the PR needs a rebase because the tests are failing?

**Comment by krainboltgreene** [comment]
Haha, sorry, it meant "I don't have notifications turned off anymore."

**Comment by krainboltgreene** [comment]
> What do you mean by this?

`git merge origin master`

**Comment by ecnalyr** [comment]
I made a pull request out of this branch that includes the necessary updates from master: https://github.com/vcr/vcr/pull/524

**Comment by krainboltgreene** [comment]
Thanks so much for your help @dnesteryuk!

**Pull request merged**
