### PR TITLE
Fix issue 517

### PR DESCRIPTION
**Pull request by mrbrdo**
Fix for #517 

I also included a commit with readme credits for the thread-safety work, mostly because I wanted to acknowledge Daniel Berger for putting up and paying out the bounty for that. Hope that's ok.

### CODE REVIEW

**Comment by djberg96** [comment]
@mrbrdo Thanks!

Seems these travis failures are not the result of your code. Rebase maybe?

**Comment by mcfiredrill** [comment]
The test suite looks to be passing, the `script/ci.sh` is failing at the end of the build for some reason though.
```
script/ci.sh: line 103: printf: `%': missing format character
The command "script/ci.sh" exited with 1.
```
Seeing the same behaviour on all ruby versions.

**Comment by mrbrdo** [comment]
Yes I noticed this too. The tests were failing before (the tests, not this printf error), and I force pushed a few times to fix those errors. So not sure what this is. Perhaps you just need to re-run the build on Travis?

**Comment by mcfiredrill** [comment]
Oh lol....I see the issue now.
Check out line 103 of `script/ci.sh`
https://github.com/vcr/vcr/blob/master/script/ci.sh#L103
```
printf "Failed: documentation coverage is less than 100%"
```

This is indeed missing the format character. The `%` should be escaped. Or its probably fine to just use echo.

Regardless, it looks like this is intended to fail the build anyway if documentation is less than 100%. As `STATUS` is set to 1 and `exit $STATUS` is called.
https://github.com/vcr/vcr/blob/master/script/ci.sh#L104

**Comment by mrbrdo** [comment]
yes definitely, will fix the documentation.

**Comment by mcfiredrill** [comment]
@mrbrdo I think so. Looks like you can run `bundle exec yard stats --list-undoc` to list the undocumented code.

**Comment by mrbrdo** [comment]
Also I knew I remembered something about this printf error... I already took a stab at it when doing #512 :) https://github.com/mrbrdo/vcr/commit/97a4ffc8507c642ce652cf5adf53ffbd5a068e7c
I guess I missed the percent issue though. But it seems the color codes weren't working either.

**Comment by mrbrdo** [comment]
It seems the build is passing now, not sure why it's not linked here...
https://travis-ci.org/vcr/vcr/builds/95870650

**Comment by mcfiredrill** [comment]
:+1:

**Comment by djberg96** [comment]
Excellent work. Please merge.

**Pull request merged**
