### PR TITLE
Help tests pass in Rubinius and a step closer for JRuby

### PR DESCRIPTION
**Pull request by mislav**
These changes help tests pass for rbx and make the situation much better on JRuby, although there are still failures.

Fixes #367, references #213

### CODE REVIEW

**Comment by mrbrdo** [comment]
I had no failures on JRuby 1.7.19 when I ran them on #512 (I did fix one minor issue first). Are they still failing for you even with #512 merged? I can look if I can help fix them if that's the case.

**Comment by mislav** [comment]
@mrbrdo: You're right, it seems that [JRuby passes now](https://travis-ci.org/vcr/vcr/jobs/85552414) in CI for this PR. Thanks for working on #512; I definitely experienced those intermittent failures before you fixed it.

**Comment by mislav** [comment]
Oh wait, it's because I disabled the multithread test in 134ea88. I'll try to re-enable it now that you've fixed it.

**Comment by mislav** [comment]
@mrbrdo There seems to be [still a failure in `concurrency_test.rb`](https://travis-ci.org/vcr/vcr/jobs/85747586)

**Comment by mrbrdo** [comment]
Can you try this fix https://github.com/mrbrdo/vcr/commit/fd6da084e99b35c7f4998e72953141d48810272e

**Comment by mrbrdo** [comment]
It could be caused by this though:
https://github.com/vcr/vcr/blob/master/lib/vcr/middleware/excon.rb#L138
And then the error occurs here: https://github.com/vcr/vcr/blob/master/lib/vcr/structs.rb#L497

But then that's not 'my' fault :)

**Comment by mislav** [comment]
It seems like you might be on the right track. But please do investigate further. You're much more familiar with this part of the codebase right now than I am.

In the meantime I feel that this PR can be merged, since it fixes rbx.

**Comment by mrbrdo** [comment]
Yes I agree. Also don't think we need to merge that commit of mine I linked above, since it's quite possible it doesn't really fix anything.

@myronmarston https://github.com/vcr/vcr/commit/e25b014e42813d509ef97a4b24b5293f5cccb4a3#diff-6d39930288e6c17dd90c201056072c11R138 Could you look into why you added line 138 here (see above comments for reference)?

**Comment by myronmarston** [comment]
> @myronmarston e25b014#diff-6d39930288e6c17dd90c201056072c11R138 Could you look into why you added line 138 here (see above comments for reference)?

I don't have any memories of writing that, but if you `git checkout e25b014`, `bundle install`, comment out line 138 and run `bundle exec rspec`, 15 excon tests fail, so it appears to be required due to how excon works. (In general, I only ever add lines like that if I can demonstrate the need through a test, so commenting out a line and seeing what tests break is always a good start with diagnosing the need for a line).  Anyhow, looking at the 15 failures, the backtrace shows it getting to that line via https://github.com/vcr/vcr/blob/e25b014e42813d509ef97a4b24b5293f5cccb4a3/lib/vcr/middleware/excon.rb#L37-L40 so it appears to have to do with a case when Excon is handling errors.  Hopefully that helps.

**Comment by krainboltgreene** [comment]
What's the state of this? Can I click the button? :3

**Pull request merged**
