### PR TITLE
Don't eject cassettes on UnhandledHTTPRequestError

### PR DESCRIPTION
**Pull request by hdabrows**
For context see the commit message and https://github.com/vcr/vcr/issues/478#issuecomment-130683370.

### CODE REVIEW

**Comment by mcfiredrill** [comment]
Sorry I'm kind of confused about what issue this is solving exactly.
In the thread you linked I closed the issue because https://github.com/vcr/vcr/pull/501 was merged.
Does https://github.com/vcr/vcr/pull/501 solve your issue?

**Comment by hdabrows** [comment]
```ruby
#!/usr/bin/env ruby

require "bundler/inline"
gemfile true do
  source "https://rubygems.org"

  gem "minitest"
  gem "vcr", "3.0.3"
  gem "webmock"
end

include WebMock::API
WebMock.enable!
WebMock.disable_net_connect!

VCR.configure do |c|
  c.cassette_library_dir = "."
  c.hook_into :webmock
end

require "minitest/autorun"
class BugTest < Minitest::Test
  def setup
    VCR.insert_cassette("cassette")
  end

  def test_bug
    begin
      Net::HTTP.get("example.com", "/#{SecureRandom.hex}")
    rescue => e
      # this will rescue VCR::Errors::UnhandledHTTPRequestError
    end
  end

  def teardown
    Net::HTTP.get("example.com", "/")
    VCR.eject_cassette
  end
end
```

Please run twice in the same directory (second run will use the cassette). Then try with `3.0.0`.

#501 included the code that ejects the cassettes on error. The reason for this was explained in https://github.com/vcr/vcr/issues/478#issuecomment-130683370. At that time the only way to get the list of all cassettes was to call a private method on `VCR` module. This is no longer the case after https://github.com/vcr/vcr/pull/529 exposed that method as private. I assume the reason why #529 preserved this behaviour (ejecting cassettes) is because the person writing the code didn't know that it was no longer necessary to do so.

**Comment by mcfiredrill** [comment]
@hdabrows Thanks alot for taking the time to write up the testcase. 💚 

I am continuing to investigate this issue, and it really helps to have this simple stripped down example.

**Comment by XrXr** [comment]
Any update on this PR? I think it also fixes #659

**Comment by krainboltgreene** [comment]
Lets get this updated from master so we can get it merged in.

**Comment by hdabrows** [comment]
@krainboltgreene I've rebased the branch on master.

**Pull request merged**
