### PR TITLE
[WIP] add ruby 2.4.0 to travis test matrix

### PR DESCRIPTION
**Pull request by mcfiredrill**

### CODE REVIEW

**Comment by bdmac** [comment]
@mcfiredrill so I forked this intending to help fix vcr compatibility with Ruby 2.4 but I've hit a bit of a snag...

All of the errors happening in vcr are actually errors in fakeweb relating to the way it is trying to mock out parts of Net::Http. Specifically there are two changes needed in fakeweb to get things working again:

1. Its monkeypatch of Net::BufferedIO has an initializer alias method chain that no longer matches the initializer of this class in 2.4. This is the root cause of all the `undefined method '<<' for {:read_timeout=>60, :continue_timeout=>nil, :debug_output=>nil}:Hash` failures in vcr. Updating the initializer override to match the new method signature and then continue to do its stubbing fixed this error.
2. After fixing that I found that fakeweb also has a `FakeWeb::StubSocket` class that is missing a stub of the (new?) `close` method that gets called by the Net::Http in 2.4. I had to add a stub `def close; @closed = true; end` basically.

Those changes make the specs in vcr pass but from what I can see nobody's maintaining fakeweb anymore so I have no idea how you guys want to proceed...

There are also a few deprecation warnings related to the merging of `Fixnum` with `Integer` in Ruby 2.4.  The diff to fix that looks like this but probably breaks < 2.4. It would need some minor version checks I guess?

```
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: spec/lib/vcr/version_spec.rb
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ version_spec.rb:15 @ describe "VCR.version" do

  describe '#major' do
    subject { super().major }
    it { should be_instance_of(Fixnum) }
    it { should be_instance_of(Integer) }
  end

  describe '#minor' do
    subject { super().minor }
    it { should be_instance_of(Fixnum) }
    it { should be_instance_of(Integer) }
  end

  describe '#patch' do
    subject { super().patch }
    it { should be_instance_of(Fixnum) }
    it { should be_instance_of(Integer) }
  end
end
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: spec/support/fixnum_extension.rb
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ fixnum_extension.rb:2 @
unless 7.respond_to?(:days)
  class Fixnum
  class Integer
    def days
      self *
      24 * # hours
```

**Comment by bdmac** [comment]
@mcfiredrill I'd push up my `vcr` branch but again all the fixes are actually to fakeweb.

**Comment by mcfiredrill** [comment]
@bdmac Thank you so much for putting in the time on this. 
Wondering what we can do about our dependency on fakeweb, looks like its been unmaintained for a few years. At least its good to hear most of the issues are coming from something we can possibly remove. 😅 

As for the warnings, I fixed them here https://github.com/vcr/vcr/pull/630 and it seems to be backwards compatible. I guess this PR needs a rebase against master.

**Comment by mcfiredrill** [comment]
Since we plan to drop fakeweb support in 4.0, I wonder if we should bother getting it to work with 2.4.
https://github.com/vcr/vcr/issues/578

**Comment by mcfiredrill** [comment]
Only thing I can think of is, if your monkeypatch is relatively simple and backwards compatible perhaps we could include it in the 3.x series and remove it in 4.0. 🤔

**Comment by 0x01f7** [comment]
This is an issue with Fakeweb rather than VCR. I think we should not include any monkeypatch in VCR library. I open a [PR](https://github.com/vcr/vcr/pull/640) to drop fakeweb support. :-)

**Comment by bdmac** [comment]
@mcfiredrill so you'd have to monkeypatch two things:

lib/fake_web/ext/net_http.rb (update init override with correct 2.4 signature)
```ruby
module Net
  class BufferedIO
    def initialize_with_fakeweb(io, read_timeout: 60, continue_timeout: nil, debug_output: nil)
      @io = io
      @read_timeout = read_timeout
      @continue_timeout = continue_timeout
      @debug_output = debug_output
      @rbuf = ''

      @io = case io
      when Socket, OpenSSL::SSL::SSLSocket, IO
        io
      when String
        if !io.include?("\0") && File.exists?(io) && !File.directory?(io)
          File.open(io, "r")
        else
          StringIO.new(io)
        end
      end
      raise "Unable to create local socket" unless @io
    end
  end
end
```

and lib/fake_web/stub_socket.rb (add `close` method to socket stub)
```ruby
module FakeWeb
  class StubSocket
    def close
      @closed = true
    end
  end
end
```

**Comment by mcfiredrill** [comment]
Closing in favor of https://github.com/vcr/vcr/pull/640

**Pull request closed without merging**
