### PR TITLE
Expect Faraday (with certain adapters at least) to support reason phrase

### PR DESCRIPTION
**Pull request by sbleon**
Most HTTP lib adapters in Faraday now expose the reason_phrase (AKA "status text") of a response. This is useful to me because some of the APIs that I work with put useful information, such as error messages, in the reason phrase. With this change, I can see the reason phrase in my recorded cassettes when using VCR with Faraday.

### CODE REVIEW

**Comment by sbleon** [comment]
This replaces #634. I've rebased and attempted to get Travis to use a recent version of Faraday. We'll see how that goes!

**Comment by sbleon** [comment]
This is not a breaking change. It should preserve compatibility with older versions of Faraday. It's just the tests that require a newer version with the new feature.

**Comment by mcfiredrill** [comment]
Thanks for your PR!
The build looks good, I will try to take a closer look at this soon. 👍

**Comment by sbleon** [comment]
@mcfiredrill could you take a look at this? It's a pretty small change to the library code. Thanks!

**Comment by ecnalyr** [comment]
LGTM
@mcfiredrill Are there any reasons why we wouldn't want to merge this?

**Comment by sbleon** [comment]
Thanks, Jason!

**Comment by mcfiredrill** [comment]
Can't really see any reason not to merge. 👍

**Pull request merged**
