### PR TITLE
PR to improve the debug message (Unhanded request error) - Updated

### PR DESCRIPTION
**Pull request by ecnalyr**
This is a continuation of the PR listed here: https://github.com/vcr/vcr/pull/501

The PR looks ready to merge, but needed to be updated to include recent changes to master.  The owner of the branch has not made updates after recent comments so I thought I would perform the necessary updates and create this PR.

### CODE REVIEW

**Comment by ecnalyr** [comment]
The failure in the Travis CI build: 
    
    expected: nil
    got: ""

**Comment by mcfiredrill** [comment]
I've seen that rbx failure happen on master as well:
https://travis-ci.org/vcr/vcr/jobs/91472719

**Comment by krainboltgreene** [comment]
So what's the next step on this?

**Comment by mcfiredrill** [comment]
Looks like the build passed the second time. I'd say good to merge.

**Pull request merged**
